# Data Science Tutorials

# Numpy Arrays

In [2]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]
# Importing numpy 
import numpy as np  

np_height = np.array(height)
np_weight = np.array(weight)
print(np_height,np_weight,type(np_height),type(np_weight))

[1.87 1.87 1.82 1.91 1.9  1.85] [81.65 97.52 95.25 92.98 86.18 88.45] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
bmi = np_weight / np_height ** 2
print(bmi)
bmi[bmi > 23]

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [5]:
type(bmi)

numpy.ndarray

In [6]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)    

# Create np_weight_lbs from np_weight_kg
np_weight_lbs = np_weight_kg*2
# Print out np_weight_lbs
print(np_weight_lbs)

[163.3  195.04 190.5  185.96 172.36 176.9 ]


# Pandas Basics

In [7]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [8]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [9]:

import pandas as pd

# Importing cars.csv
cars = pd.read_csv('cars.csv')

# Print out cars
print(cars)

    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
NaN         RU           200         Russia          True
NaN        MOR            70        Morocco          True
NaN         EG            45          Egypt          True


In [10]:
# Import pandas and cars.csv
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out DataFrame with country and drives_right columns
print(cars[['cars_per_cap', 'country']])

     cars_per_cap        country
NaN           809  United States
NaN           731      Australia
NaN           588          Japan
NaN            18          India
NaN           200         Russia
NaN            70        Morocco
NaN            45          Egypt


In [26]:
# Print out first 4 observations
print(cars.iloc[0:4])

# Print out fifth and sixth observations
print(cars.iloc[4:6])

    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
    Unnamed: 0  cars_per_cap  country  drives_right
NaN         RU           200   Russia          True
NaN        MOR            70  Morocco          True


In [34]:
# Load the CSV without setting an index
cars = pd.read_csv('cars.csv')

# Set the first column as the index
cars.set_index(cars.columns[0], inplace=True)

In [35]:
cars.index

Index(['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG'], dtype='object', name='Unnamed: 0')

In [37]:
# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

            cars_per_cap    country  drives_right
Unnamed: 0                                       
AUS                  731  Australia         False
EG                    45      Egypt          True
